/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://y6fglhzxavfdjgwh5kmvgdlgoi.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-67lo57chsnddtn4mrwtc7wsf7a",
    "aws_cognito_identity_pool_id": "us-east-1:ad63ccf5-aedd-4a55-afc4-c08f567e38b0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_i96t7A8ME",
    "aws_user_pools_web_client_id": "3kf86vqa59m5iro3hdjmqhgp60",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
